version: '3.2'
services:
  db:
    build:
      context: docker
      dockerfile: postgres/postgres.dockerfile
    environment:
      POSTGRES_VERSION: ${POSTGRES_VERSION}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORTS}:5432
    networks:
      - picsumPhotos
  front:
    build:
      context: ./docker/nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./:/var/www
    depends_on:
      - backend
    networks:
      - picsumPhotos
  backend: #&app
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: db
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    networks:
      - picsumPhotos
networks:
  picsumPhotos:
    driver: bridge

volumes:
  postgres: